cicd/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from cicd import views

app_name = "cicd"

urlpatterns = [
    path("", views.CicdScanList.as_view(), name="cicd_list"),
    path("scannercmd/", views.ScannerCommand.as_view(), name="scannercmd"),
    path("createpolicies/", views.CreatePolicies.as_view(), name="createpolicies"),
    path("deletepolicies/", views.PoliciesDelete.as_view(), name="deletepolicies"),
    path(
        "policiesedit/<str:uu_id>/", views.PoliciesEdit.as_view(), name="policiesedit"
    ),
]

cloudscanners/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from cloudscanners import views

app_name = "cloudscanners"

urlpatterns = [
    # Static scans
    path("list_vuln/", views.CloudScanVulnList.as_view(), name="list_vuln"),
    path("list_scans/", views.CloudScanList.as_view(), name="list_scans"),
    path("list_vuln_info/", views.CloudScanVulnInfo.as_view(), name="list_vuln_info"),
    path("scan_details/", views.CloudScanDetails.as_view(), name="scan_details"),
    path("scan_delete/", views.CloudScanDelete.as_view(), name="scan_delete"),
    path("vuln_delete/", views.CloudScanVulnDelete.as_view(), name="vuln_delete"),
    path("vuln_mark/", views.CloudScanVulnMark.as_view(), name="vuln_mark"),
]

jiraticketing/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from jiraticketing import views

app_name = "jiraticketing"

urlpatterns = [
    path("jira_setting/", views.JiraSetting.as_view(), name="jira_setting"),
    path(
        "submit_jira_ticket/",
        views.CreateJiraTicket.as_view(),
        name="submit_jira_ticket",
    ),
    path(
        "link_jira_ticket/",
        views.LinkJiraTicket.as_view(),
        name="link_jira_ticket",
    ),
]

report_upload/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.
from django.urls import include, path

from report_upload import views

app_name = "report_upload"

urlpatterns = [
    path("upload/", views.Upload.as_view(), name="upload"),
]

cloudscanners/views.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from __future__ import unicode_literals

import hashlib

from django.core import signing
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse
from jira import JIRA
from notifications.models import Notification
from notifications.signals import notify
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from cloudscanners.models import CloudScansDb, CloudScansResultsDb
from cloudscanners.serializers import (CloudScanDbSerializer,
                                       CloudScanResultsDbSerializer)
from jiraticketing.models import jirasetting
from user_management import permissions


class CloudScanList(APIView):
    permission_classes = [IsAuthenticated | permissions.VerifyAPIKey]

    def get(self, request):
        scan_list = CloudScansDb.objects.filter(organization=request.user.organization)
        all_notify = Notification.objects.unread()

        if request.path[:4] == "/api":
            serialized_data = CloudScanDbSerializer(scan_list, many=True)
            return Response(serialized_data.data)
        else:
            return render(
                request,
                "cloudscanners/scans/list_scans.html",
                {"all_scans": scan_list, "message": all_notify},
            )


class CloudScanVulnInfo(APIView):
    permission_classes = [IsAuthenticated | permissions.VerifyAPIKey]

    def get(self, request, uu_id=None):
        jira_url = None
        jira = jirasetting.objects.filter(organization=request.user.organization)
        for d in jira:
            jira_url = d.jira_server

        # all_notify =
        Notification.objects.unread()
        if uu_id is None:
            scan_id = request.GET["scan_id"]
            scan_name = request.GET["scan_name"]
            vuln_data = CloudScansResultsDb.objects.filter(
                scan_id=scan_id, title=scan_name, organization=request.user.organization
            )
        else:
            try:
                vuln_data = CloudScansResultsDb.objects.filter(
                    scan_id=uu_id, organization=request.user.organization
                )
            except Exception:
                return Response(
                    {"message": "Scan Id Doesn't Exist"},
                    status=status.HTTP_404_NOT_FOUND,
                )
        if request.path[:4] == "/api":
            serialized_data = CloudScanResultsDbSerializer(vuln_data, many=True)
            return Response(serialized_data.data)
        else:
            return render(
                request,
                "cloudscanners/scans/list_vuln_info.html",
                {"vuln_data": vuln_data, "jira_url": jira_url},
            )


class CloudScanVulnMark(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "cloudscanners/scans/list_vuln_info.html"

    permission_classes = (IsAuthenticated, permissions.IsAnalyst)

    def post(self, request):
        false_positive = request.POST.get("false")
        status = request.POST.get("status")
        vuln_id = request.POST.get("vuln_id")
        scan_id = request.POST.get("scan_id")
        vuln_name = request.POST.get("vuln_name")
        notes = request.POST.get("note")
        CloudScansResultsDb.objects.filter(
            vuln_id=vuln_id, scan_id=scan_id, organization=request.user.organization
        ).update(false_positive=false_positive, vuln_status=status, note=notes)

        if false_positive == "Yes":
            vuln_info = CloudScansResultsDb.objects.filter(
                scan_id=scan_id, vuln_id=vuln_id, organization=request.user.organization
            )
            for vi in vuln_info:
                policy_name = vi.title
                cloud_account_id = vi.cloudAccountId
                resource_id = vi.resourceId
                severity = vi.severity
                dup_data = (
                    str(policy_name)
                    + str(severity)
                    + str(cloud_account_id)
                    + str(resource_id)
                )

                false_positive_hash = hashlib.sha256(
                    dup_data.encode("utf-8")
                ).hexdigest()
                CloudScansResultsDb.objects.filter(
                    vuln_id=vuln_id,
                    scan_id=scan_id,
                    organization=request.user.organization,
                ).update(
                    false_positive=false_positive,
                    vuln_status="Closed",
                    false_positive_hash=false_positive_hash,
                    note=notes,
                )

        all_vuln = CloudScansResultsDb.objects.filter(
            scan_id=scan_id,
            false_positive="No",
            vuln_status="Open",
            organization=request.user.organization,
        )

        total_high = len(all_vuln.filter(severity="High"))
        total_medium = len(all_vuln.filter(severity="Medium"))
        total_low = len(all_vuln.filter(severity="Low"))
        total_info = len(all_vuln.filter(severity="Informational"))
        total_dup = len(all_vuln.filter(vuln_duplicate="Yes"))
        total_vul = total_high + total_medium + total_low + total_info

        CloudScansDb.objects.filter(
            scan_id=scan_id, organization=request.user.organization
        ).update(
            total_vul=total_vul,
            high_vul=total_high,
            medium_vul=total_medium,
            low_vul=total_low,
            info_vul=total_info,
            total_dup=total_dup,
        )
        return HttpResponseRedirect(
            reverse("cloudscanners:list_vuln_info")
            + "?scan_id=%s&scan_name=%s" % (scan_id, vuln_name)
        )


class CloudScanDetails(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "cloudscanners/scans/vuln_details.html"

    permission_classes = (IsAuthenticated, permissions.IsViewer)

    def get(self, request):
        jira_server = None
        jira_username = None
        jira_password = None
        jira_projects = None
        vuln_id = request.GET["vuln_id"]
        jira_setting = jirasetting.objects.filter()
        # user = request.user

        for jira in jira_setting:
            jira_server = jira.jira_server
            jira_username = jira.jira_username
            jira_password = jira.jira_password

        if jira_username is not None:
            jira_username = signing.loads(jira_username)

        if jira_password is not None:
            jira_password = signing.loads(jira_password)

        options = {"server": jira_server}
        try:
            if jira_username is not None and jira_username != "":
                jira_ser = JIRA(
                    options,
                    basic_auth=(jira_username, jira_password),
                    max_retries=0,
                    timeout=30,
                )
            else:
                jira_ser = JIRA(
                    options, token_auth=jira_password, max_retries=0, timeout=30
                )

            jira_projects = jira_ser.projects()
        except Exception as e:
            print(e)
            jira_projects = None
            # notify.send(user, recipient=user, verb="Jira settings not found")

        vul_dat = CloudScansResultsDb.objects.filter(
            vuln_id=vuln_id, organization=request.user.organization
        ).order_by("vuln_id")

        return render(
            request,
            "cloudscanners/scans/vuln_details.html",
            {"vul_dat": vul_dat, "jira_projects": jira_projects},
        )


class CloudScanDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "cloudscanners/scans/list_scans.html"

    permission_classes = (
        IsAuthenticated,
        permissions.IsAnalyst,
    )

    def post(self, request):
        scan_id = request.POST.get("scan_id")

        scan_item = str(scan_id)
        value = scan_item.replace(" ", "")
        value_split = value.split(",")
        split_length = value_split.__len__()
        # print "split_length", split_length
        for i in range(0, split_length):
            scan_id = value_split.__getitem__(i)

            item = CloudScansDb.objects.filter(
                scan_id=scan_id, organization=request.user.organization
            )
            item.delete()
            item_results = CloudScansResultsDb.objects.filter(
                scan_id=scan_id, organization=request.user.organization
            )
            item_results.delete()
        return HttpResponseRedirect(reverse("cloudscanners:list_scans"))


class CloudScanVulnDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "cloudscanners/scans/list_vuln_info.html"

    permission_classes = (IsAuthenticated, permissions.IsAnalyst)

    def post(self, request):
        vuln_id = request.POST.get("vuln_id")
        scan_id = request.POST.get("scan_id")

        scan_item = str(vuln_id)
        value = scan_item.replace(" ", "")
        value_split = value.split(",")
        split_length = value_split.__len__()
        # print "split_length", split_length
        for i in range(0, split_length):
            vuln_id = value_split.__getitem__(i)
            delete_vuln = CloudScansResultsDb.objects.filter(
                vuln_id=vuln_id, organization=request.user.organization
            )
            delete_vuln.delete()

templates/cloudscanners/scans/list_scans.html
{% extends 'dashboard/base.html' %}

{% block body %}
<script type="text/javascript">

    $("#checkAll").change(function () {
        $("input:checkbox").prop('checked', $(this).prop("checked"));
    });
    $(document).ready(function() {
        $('.btn-danger').click(function(){
            if (confirm('Are you sure you want to delete this?')) {
                var scan_id = ['a7af5b68-b661-45ad-90fd-ffa27526cdce'];
                $.each($("input[name='del_scan_id']:checked"), function(){
                    scan_id.push($(this).val());
                });

                var json_scanid = scan_id.join(", ");
                $.ajax({
                    type:'POST',
                    <!--contentType: 'application/json; charset=utf-8',-->
                    url:'{% url 'cloudscanners:scan_delete' %}',
                    data:{
                       scan_id: json_scanid,
                       csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    sucess:function(){

                    }
                });
                setTimeout(function(){location.reload();},1200);
            }
        });

    });

</script>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="float-right">
                           {% if user.is_superuser == True or user.role.id == 2 %}
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{% url 'report_upload:upload' %}" class="btn btn-primary btn-mini" data-toggle="tooltip" data-placement="top" title="Upload Report"><i
                                        class="fas fa-upload
"></i> Upload</a>
                            </div>
                            <button type="button" class="btn btn-danger btn-mini" onclick="">Delete Selected</button>
                            {% endif %}
                        </div>
                        <br>
                        <br>
                        <br>
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Cloud Scans List</h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="table-responsive">
                                <table id="data_table" class="table table-bordered data-table">
                            <thead>
                            <tr>
                                <th><label class="customcheckbox m-b-20">
                                <input type="checkbox" id="mainCheckbox">
                                <span class="checkmark"></span>
                                </label></th>
                                <th>Account ID</th>
                                <th>Scanner</th>
                                <th>Date Time</th>
                                <th>Total</th>
                                <th>Critical</th>
                                <th>High</th>
                                <th>Medium</th>
                                <th>Low</th>
                                <th>Duplicates</th>
                            </tr>
                            </thead>
                            <tbody>{% for data in all_scans %}
                            <tr data-target="#">
                                <td>{% csrf_token %}
                                            <form>
                                                <label class="customcheckbox">
                                                    <input type="checkbox" class="listCheckbox"
                                                           value="{{data.scan_id}}"
                                                           name="del_scan_id"
                                                           onClick="reload">
                                                    <span class="checkmark"></span>
                                                </label>
                                            </form>
                                        </td>

                                <td>
                                    <a href="{% url 'cloudscanners:list_vuln' %}?scan_id={{data.scan_id}}&scanner={{ data.scanner }}">{% firstof data.cloudAccountId 'None' %}</a>
                                </td>
                                <td>
                                    {% with scanType=data.scanner %}
                                    <div class="p-1"><img src="{{ PARSER_DICT | get_icon:scanType }}" alt="user"
                                            width="30" class="rounded-circle" data-toggle="tooltip"
                                            data-placement="top"
                                            title="{{ PARSER_DICT | get_displayName:scanType }}">
                                    </div>
                                    {% endwith %}
                                </td>
                                <td>{{data.date_time}}</td>
                                <td><span class="badge badge-pill badge-dark">{{data.total_vul}}</span></td>
                                <td><span class="badge badge-pill badge-critical">{{data.critical_vul}}</span></td>
                                <td><span class="badge badge-pill badge-danger">{{data.high_vul}}</span></td>
                                <td><span class="badge badge-pill badge-warning">{{data.medium_vul}}</span></td>
                                <td><span class="badge badge-pill badge-info">{{data.low_vul}}</span></td>
                                <td><span class="badge badge-pill badge-secondary">{{data.total_dup}}</span></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/cloudscanners/scans/list_vuln.html
{% extends 'dashboard/base.html' %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <br>
                    <div class="d-md-flex align-items-center">
                        <h1 class="card-title">Vulnerability List</h1>
                    </div>
                    <br>
                    <div class="row">
                        <div class="table-responsive">
                           <table id="data_table" class="table table-bordered data-table table-fixed"
                                       width="100%">
                                <thead>
                                <tr>
                                    <th>Issues</th>
                                    <th>Status</th>
                                    <th>Risk</th>
                                </tr>
                                </thead>
                                 <tbody>{% for data in all_vuln %}
                                    <tr data-target="#">
                                        <td>
                                            <a href="{% url 'cloudscanners:list_vuln_info' %}?scan_id={{ data.scan_id }}&scan_name={{ data.title }}&scanner={{ data.scanner }}">{{ data.title }}</a>
                                        </td>
                                        {% if data.vuln_status == 'Open' %}
                                            <td><span class="badge badge-pill badge-purple">{{ data.vuln_status }}</span>
                                                {% if data.note != None %}
                                                    <i data-toggle="tooltip" data-placement="top" title data-original-title="{{data.note}}" class="fas fa-comment-alt"></i>
                                                {% endif %}
                                            </td>
                                        {% endif %}
                                        {% if data.vuln_status == 'Closed' %}
                                        <td><span class="badge badge-pill badge-success">{{data.vuln_status}}</span>
                                        {% if data.note != None %}
                                            <i data-toggle="tooltip" data-placement="top" title data-original-title="{{data.note}}" class="fas fa-comment-alt"></i>
                                        {% endif %}

                                        </td>
                                        {% endif %}

                                        {% if data.vuln_status == 'Duplicate' %}
                                            <td><span class="badge badge-pill badge-warning">{{ data.vuln_status }}</span>
                                                {% if data.note != None %}
                                                    <i data-toggle="tooltip" data-placement="top" title data-original-title="{{data.note}}" class="fas fa-comment-alt"></i>
                                                {% endif %}
                                            </td>
                                        {% endif %}
                                        <td><span class="badge badge-pill badge-{{ data.severity_color }}">{{ data.severity }}</span>
                                        </td>
                                    </tr>
                                 {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}