cicd/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from cicd import views

app_name = "cicd"

urlpatterns = [
    path("", views.CicdScanList.as_view(), name="cicd_list"),
    path("scannercmd/", views.ScannerCommand.as_view(), name="scannercmd"),
    path("createpolicies/", views.CreatePolicies.as_view(), name="createpolicies"),
    path("deletepolicies/", views.PoliciesDelete.as_view(), name="deletepolicies"),
    path(
        "policiesedit/<str:uu_id>/", views.PoliciesEdit.as_view(), name="policiesedit"
    ),
]

report_upload/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.
from django.urls import include, path

from report_upload import views

app_name = "report_upload"

urlpatterns = [
    path("upload/", views.Upload.as_view(), name="upload"),
]

webscanners/burpscanner/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from webscanners.burpscanner import views

app_name = "burpscanner"

urlpatterns = [
    # Burp scans
    path("burp_launch_scan/", views.BurpScanLaunch.as_view(), name="burp_launch_scan"),
    path("export/", views.export, name="export"),
    path("burp_setting/", views.BurpSetting.as_view(), name="burp_setting"),
]

webscanners/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from webscanners import views, web_views

app_name = "webscanners"

urlpatterns = [
    path("", web_views.Index.as_view(), name="index"),
    path(
        "cookie_add/",
        web_views.AddCookies.as_view(),
        name="cookie_add",
    ),
    path("web_task_launch/", web_views.WebTaskLaunch.as_view(), name="web_task_launch"),
    path(
        "web_scan_schedule/",
        web_views.WebScanSchedule.as_view(),
        name="web_scan_schedule",
    ),
    path(
        "del_web_scan_schedule/",
        web_views.WebScanScheduleDelete.as_view(),
        name="del_web_scan_schedule",
    ),
    path("del_notify/", web_views.DeleteNotify.as_view(), name="del_notify"),
    path("del_all_notify/", web_views.DeleteAllNotify.as_view(), name="del_all_notify"),
    # Dynamic scans
    path("list_vuln/", views.WebScanVulnList.as_view(), name="list_vuln"),
    path("list_scans/", views.WebScanList.as_view(), name="list_scans"),
    path("list_vuln_info/", views.WebScanVulnInfo.as_view(), name="list_vuln_info"),
    path("scan_details/", views.WebScanDetails.as_view(), name="scan_details"),
    path("scan_delete/", views.WebScanDelete.as_view(), name="scan_delete"),
    path("vuln_delete/", views.WebScanVulnDelete.as_view(), name="vuln_delete"),
    path("vuln_mark/", views.WebScanVulnMark.as_view(), name="vuln_mark"),
]

webscanners/zapscanner/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from webscanners.zapscanner import views

app_name = "zapscanner"

urlpatterns = [
    path("zap_scan/", views.ZapScan.as_view(), name="zap_scan"),
    path("zap_settings/", views.ZapSetting.as_view(), name="zap_settings"),
    path(
        "zap_setting_update/",
        views.ZapSettingUpdate.as_view(),
        name="zap_setting_update",
    ),
]

webscanners/arachniscanner/views.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from __future__ import unicode_literals

import hashlib
import json
import threading
import time
import uuid
from datetime import datetime

import defusedxml.ElementTree as ET
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from notifications.signals import notify
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

import PyArachniapi
from archerysettings.models import ArachniSettingsDb, SettingsDb
from jiraticketing.models import jirasetting
from projects.models import ProjectDb
from scanners.scanner_parser.web_scanner import arachni_xml_parser
from user_management import permissions
from webscanners.arachniscanner.serializers import (ArachniScansSerializer,
                                                    ArachniSettingsSerializer)
from webscanners.models import WebScanResultsDb, WebScansDb
from webscanners.resources import ArachniResource

scan_run_id = ""
scan_status = ""


def launch_arachni_scan(target, project_id, rescan_id, rescan, scan_id, user):
    global scan_run_id, scan_status
    arachni_hosts = None
    arachni_ports = None
    arachni_user = ""
    arachni_pass = ""
    all_arachni = ArachniSettingsDb.objects.filter()
    for arachni in all_arachni:
        arachni_hosts = arachni.arachni_url
        arachni_ports = arachni.arachni_port
        arachni_user = arachni.arachni_user
        arachni_pass = arachni.arachni_pass

    arachni = PyArachniapi.arachniAPI(
        arachni_hosts, arachni_ports, arachni_user, arachni_pass
    )
    check = [
        "xss_event",
        "xss",
        "xss_script_context",
        "xss_tag",
        "xss_path",
        "xss_dom_script_context",
        "xss_dom",
        "sql_injection",
        "sql_injection_differential",
        "sql_injection_timing",
        "no_sql_injection",
        "no_sql_injection_differential",
        "code_injection",
        "code_injection_timing",
        "ldap_injection",
        "path_traversal",
        "file_inclusion",
        "response_splitting",
        "os_cmd_injection",
        "os_cmd_injection_timing",
        "rfi",
        "unvalidated_redirect",
        "unvalidated_redirect_dom",
        "xpath_injection",
        "xxe",
        "source_code_disclosure",
        "allowed_methods",
        "backup_files",
        "backup_directories",
        "common_admin_interfaces",
        "common_directories",
        "common_files",
        "http_put",
        "webdav",
        "xst",
        "credit_card",
        "cvs_svn_users",
        "private_ip",
        "backdoors",
        "htaccess_limit",
        "interesting_responses",
        "html_objects",
        "emails",
        "ssn",
        "directory_listing",
        "mixed_resource",
        "insecure_cookies",
        "http_only_cookies",
        "password_autocomplete",
        "origin_spoof_access_restriction_bypass",
        "form_upload",
        "localstart_asp",
        "cookie_set_for_parent_domain",
        "hsts",
        "x_frame_options",
        "insecure_cors_policy",
        "insecure_cross_domain_policy_access",
        "insecure_cross_domain_policy_headers",
        "insecure_client_access_policy",
        "csrf",
        "common_files",
        "directory_listing",
    ]

    data = {"url": target, "checks": check, "audit": {}}
    d = json.dumps(data)

    scan_launch = arachni.scan_launch(d)
    time.sleep(3)

    try:
        scan_data = scan_launch.data

        for key, value in scan_data.items():
            if key == "id":
                scan_run_id = value
        notify.send(
            user, recipient=user, verb="Arachni Scan Started on URL %s" % target
        )
    except Exception:
        notify.send(user, recipient=user, verb="Arachni Connection Not found")
        print("Arachni Connection Not found")
        return

    date_time = datetime.now()

    try:
        save_all_scan = WebScansDb(
            project_id=project_id,
            scan_url=target,
            scan_id=scan_id,
            date_time=date_time,
            scanner="Arachni",
        )

        save_all_scan.save()

    except Exception as e:
        print(e)

    scan_data = scan_launch.data

    for key, value in scan_data.items():
        if key == "id":
            scan_run_id = value

    scan_sum = arachni.scan_summary(id=scan_run_id).data
    for key, value in scan_sum.items():
        if key == "status":
            scan_status = value
    while scan_status != "done":
        status = "0"
        if (
            scan_sum["statistics"]["browser_cluster"]["queued_job_count"]
            and scan_sum["statistics"]["browser_cluster"]["total_job_time"]
        ):
            status = (
                100
                - scan_sum["statistics"]["browser_cluster"]["queued_job_count"]
                * 100
                / scan_sum["statistics"]["browser_cluster"]["total_job_time"]
            )
        WebScansDb.objects.filter(scan_id=scan_id, scanner="Arachni").update(
            scan_status=int(status)
        )
        scan_sum = arachni.scan_summary(id=scan_run_id).data
        for key, value in scan_sum.items():
            if key == "status":
                scan_status = value
        time.sleep(3)
    if scan_status == "done":
        xml_report = arachni.scan_xml_report(id=scan_run_id).data
        root_xml = ET.fromstring(xml_report)
        arachni_xml_parser.xml_parser(
            project_id=project_id,
            scan_id=scan_id,
            root=root_xml,
            target_url=target,
        )
        WebScansDb.objects.filter(scan_id=scan_id, scanner="Arachni").update(
            scan_status="100"
        )
        print("Data uploaded !!!!")

    notify.send(user, recipient=user, verb="Arachni Scan Completed on URL %s" % target)


class ArachniScan(APIView):
    permission_classes = (IsAuthenticated, permissions.IsAnalyst)

    def get(self, request):
        return render(request, "webscanners/webscanner.html")

    def post(self, request):
        scan_id = None
        project_uu_id = None
        target_url = None

        user = request.user
        if request.path[:4] == "/api":
            serializer = ArachniScansSerializer(data=request.data)
            if serializer.is_valid():
                target_url = request.data.get(
                    "url",
                )
                project_uu_id = request.data.get(
                    "project_id",
                )
        else:
            target_url = request.POST.get("scan_url")
            project_uu_id = request.POST.get("project_id")
        project_id = (
            ProjectDb.objects.filter(uu_id=project_uu_id).values("id").get()["id"]
        )
        rescan_id = None
        rescan = "No"
        target_item = str(target_url)
        value = target_item.replace(" ", "")
        target__split = value.split(",")
        split_length = target__split.__len__()
        for i in range(0, split_length):
            target = target__split.__getitem__(i)
            scan_id = uuid.uuid4()
            thread = threading.Thread(
                target=launch_arachni_scan,
                args=(target, project_id, rescan_id, rescan, scan_id, user),
            )
            thread.daemon = True
            thread.start()

            if request.path[:4] == "/api":
                return Response({"scan_id": scan_id})

        if request.path[:4] == "/api":
            return Response({"scan_id": scan_id})
        else:
            return render(request, "webscanners/scans/list_scans.html")


class ArachniSetting(APIView):
    permission_classes = (IsAuthenticated, permissions.IsAnalyst)

    def get(self, request):
        arachni_hosts = None
        arachni_ports = None
        arachni_user = None
        arachni_pass = None

        all_arachni = ArachniSettingsDb.objects.filter()
        for arachni in all_arachni:
            # global arachni_api_key, arachni_hosts, arachni_ports
            arachni_hosts = arachni.arachni_url
            arachni_ports = arachni.arachni_port
            arachni_user = arachni.arachni_user
            arachni_pass = arachni.arachni_pass

        if request.path[:4] == "/api":
            return Response(
                {
                    "arachni_host": arachni_hosts,
                    "arachni_port": arachni_ports,
                    "arachni_user": arachni_user,
                    "arachni_pass": arachni_pass,
                }
            )
        else:
            return render(
                request,
                "webscanners/arachniscanner/arachni_settings_form.html",
                {
                    "arachni_host": arachni_hosts,
                    "arachni_port": arachni_ports,
                    "arachni_user": arachni_user,
                    "arachni_pass": arachni_pass,
                },
            )


class ArachniSettingUpdate(APIView):
    permission_classes = (IsAuthenticated, permissions.IsAnalyst)

    def get(self, request):
        return render(request, "webscanners/arachniscanner/arachni_settings_form.html")

    def post(self, request):
        setting_id = uuid.uuid4()
        arachnihost = None
        port = None
        user = None
        password = None

        if request.path[:4] == "/api":

templates/webscanners/scans/list_scans.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block body %}
<script type="text/javascript">

    $("#checkAll").change(function () {
        $("input:checkbox").prop('checked', $(this).prop("checked"));
    });
    $(document).ready(function() {
        $('.btn-danger').click(function(){
            if (confirm('Are you sure you want to delete this?')) {
                var scan_id = ['a7af5b68-b661-45ad-90fd-ffa27526cdce'];
                $.each($("input[name='del_scan_id']:checked"), function(){
                    scan_id.push($(this).val());
                });

                var json_scanid = scan_id.join(", ");
                $.ajax({
                    type:'POST',
                    <!--contentType: 'application/json; charset=utf-8',-->
                    url:'{% url 'webscanners:scan_delete' %}',
                    data:{
                       scan_id: json_scanid,
                       csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    sucess:function(){

                    }
                });
                setTimeout(function(){location.reload();},1000);
            }
        });

    });

    $(document).ready(function() {
        $('.btn-primary').click(function(){
                var scan_id = ['a7af5b68-b661-45ad-90fd-ffa27526cdce'];
                $.each($("input[name='del_scan_id']:checked"), function(){
                    scan_id.push($(this).val());
                });

            document.getElementById("toexport").value = scan_id.join(", ");


        });

    });


</script>


        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                    {% if user.is_superuser == True or user.role.id == 2 %}
                        <div class="float-right">

                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{% url 'report_upload:upload' %}" class="btn btn-primary btn-mini" data-toggle="tooltip" data-placement="top" title="Upload XML Report"><i
                                        class="fas fa-upload"></i> Upload </a>
                            </div>
                            <button type="button" class="btn btn-danger btn-mini" onclick="">Delete Selected</button>

                        </div>
                    {% endif %}
                        <br>
                        <br>
                        {% csrf_token %}
{#                        <div class="float-right">#}
{#                            <form action="{% url 'webscanners:export' %}" method="post"#}
{#                                  class="forms-sample">#}
{#                                {% csrf_token %}#}
{#                                <div class="form-row align-items-center">#}
{#                                    <div class="col-auto my-1">#}
{#                                        <select name="type" class="custom-select mr-sm-2" id="inlineFormCustomSelect">#}
{#                                            <option value="csv" selected>CSV</option>#}
{#                                            <option value="json">JSON</option>#}
{#                                            <option value="yaml">YAML</option>#}
{#                                        </select>#}
{#                                    </div>#}
{#                                    <div class="col-auto my-1">#}
{#                                         <input type="hidden" id="toexport" name="scan_id"/>#}
{#                                        <button type="submit" class="btn btn-primary"><i#}
{#                                                class="fas fa-arrow-alt-circle-down"></i></button>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </form>#}
{#                        </div>#}
                        <br>
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Dynamic Scans List</h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="table-responsive">
                                <table id="data_table" class="table table-bordered data-table">
                                    <thead>
                                    <tr>
                                        <th><label class="customcheckbox m-b-20">
                                            <input type="checkbox" id="mainCheckbox">
                                            <span class="checkmark"></span>
                                        </label></th>
                                        <th>URL</th>
                                        <th>Status</th>
                                        <th>Scanner</th>
                                        <th>Total Vulnerability</th>
                                        <th>Critical</th>
                                        <th>High</th>
                                        <th>Medium</th>
                                        <th>Low</th>
                                        <th>Info</th>
                                        <th>Duplicates</th>
                                    </tr>
                                    </thead>
                                    <tbody>{% for data in all_scans %}
                                    <tr data-target="#">
                                        <td>
                                            <form>
                                                <label class="customcheckbox">
                                                    <input type="checkbox" class="listCheckbox"
                                                           value="{{data.scan_id}}"
                                                           name="del_scan_id"
                                                           onClick="reload">
                                                    <span class="checkmark"></span>
                                                </label>
                                            </form>
                                        </td>
                                        <td>
                                            <a href="{% url 'webscanners:list_vuln' %}?scan_id={{data.scan_id}}">{{data.scan_url}}</a>
                                        </td>
                                        <td width="20%">
                                            <div>
                                                <div class="d-flex no-block align-items-center">
                                                    <span>{{data.scan_status}}% Completed</span>
                                                </div>
                                                <div class="progress{% if data.scan_status != '100.0' %} active progress-striped{% endif %}">
                                                    <div class="progress-bar progress-bar-striped" role="progressbar"
                                                         style="width: {{data.scan_status}}{{data.vul_status}}%"
                                                         aria-valuenow="10" aria-valuemin="0"
                                                         aria-valuemax="100"></div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>{% with scanType=data.scanner %}
                                            <div class="p-1"><img src="{{ PARSER_DICT | get_icon:scanType }}" alt="user"
                                                    width="30" class="rounded-circle" data-toggle="tooltip"
                                                    data-placement="top"
                                                    title="{{ PARSER_DICT | get_displayName:scanType }}">
                                            </div>
                                            {% endwith %}
                                        </td>

                                        <td><span class="badge badge-pill badge-dark">{{data.total_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-critical">{{data.critical_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-danger">{{data.high_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-warning">{{data.medium_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-info">{{data.low_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-info">{{data.info_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-secondary">{{data.total_dup}}</span></td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/webscanners/scans/list_vuln.html
{% extends 'dashboard/base.html' %}

{% block body %}

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <br>
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Vulnerability List</h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="table-responsive">
                                <table id="data_table" class="table table-bordered data-table table-fixed"
                                       width="100%">
                                    <thead>
                                    <tr>
                                        <th>Vulnerability</th>
                                        <th>Status</th>
                                        <th>Risk</th>
                                    </tr>
                                    </thead>
                                    <tbody>{% for data in all_vuln %}
                                    <tr data-target="#">
                                        <td>
                                            <a href="{% url 'webscanners:list_vuln_info' %}?scan_id={{data.scan_id}}&scan_name={{data.title}}">{{data.title}}</a>
                                        </td>
                                        {% if data.vuln_status == 'Open' %}
                                        <td><span class="badge badge-pill badge-purple">{{data.vuln_status}}</span>
                                        {% if data.note != None %}
                                            <i data-toggle="tooltip" data-placement="top" title data-original-title="{{data.note}}" class="fas fa-comment-alt"></i>
                                        {% endif %}
                                        </td>
                                        {% endif %}
                                        {% if data.vuln_status == 'Closed' %}
                                        <td><span class="badge badge-pill badge-success">{{data.vuln_status}}</span>
                                        {% if data.note != None %}
                                         <i data-toggle="tooltip" data-placement="top" title data-original-title="{{data.note}}" class="fas fa-comment-alt"></i>
                                        {% endif %}
                                        </td>
                                        {% endif %}
                                        {% if data.vuln_status == 'Duplicate' %}
                                        <td><span class="badge badge-pill badge-warning">{{data.vuln_status}}</span></td>
                                        {% endif %}
                                        <td><span class="badge badge-pill badge-{{data.severity_color}}">{{data.severity}}</span>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}