cicd/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from cicd import views

app_name = "cicd"

urlpatterns = [
    path("", views.CicdScanList.as_view(), name="cicd_list"),
    path("scannercmd/", views.ScannerCommand.as_view(), name="scannercmd"),
    path("createpolicies/", views.CreatePolicies.as_view(), name="createpolicies"),
    path("deletepolicies/", views.PoliciesDelete.as_view(), name="deletepolicies"),
    path(
        "policiesedit/<str:uu_id>/", views.PoliciesEdit.as_view(), name="policiesedit"
    ),
]

networkscanners/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from networkscanners import views

app_name = "networkscanners"

urlpatterns = [
    path("launch_scan/", views.OpenvasLaunchScan.as_view(), name="launch_scan"),
    path("ip_scan/", views.NetworkScan.as_view(), name="ip_scan"),
    path("nv_setting/", views.OpenvasSettingEnable.as_view(), name="nv_setting"),
    path("nv_details/", views.OpenvasSettingEnableDetails.as_view(), name="nv_details"),
    path("openvas_setting/", views.OpenvasSetting.as_view(), name="openvas_setting"),
    path("openvas_details/", views.OpenvasDetails.as_view(), name="openvas_details"),
    path(
        "net_scan_schedule/",
        views.NetworkScanSchedule.as_view(),
        name="net_scan_schedule",
    ),
    path(
        "del_net_scan_schedule/",
        views.NetworkScanScheduleDelete.as_view(),
        name="del_net_scan_schedule",
    ),
    path("list_scans/", views.NetworkScanList.as_view(), name="list_scans"),
    path("list_vuln_info/", views.NetworkScanVulnInfo.as_view(), name="list_vuln_info"),
    path("scan_details/", views.NetworkScanDetails.as_view(), name="scan_details"),
    path("scan_delete/", views.NetworkScanDelete.as_view(), name="scan_delete"),
    path("vuln_delete/", views.NetworkScanVulnDelete.as_view(), name="vuln_delete"),
    path("vuln_mark/", views.NetworkScanVulnMark.as_view(), name="vuln_mark"),
]

pentest/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from pentest import views

app_name = "pentest"

urlpatterns = [
    path("", views.PentestList.as_view(), name="list_scan"),
    path("add_vuln/", views.PentestVulnCreate.as_view(), name="add_vuln"),
    path("vuln_list/", views.PentestListVuln.as_view(), name="vuln_list"),
    path("edit_vuln/", views.EditPentestVuln.as_view(), name="edit_vuln"),
    path("manual_vuln_data/", views.PentestVulnData.as_view(), name="manual_vuln_data"),
    path("del_vuln/", views.PentestVulnDelete.as_view(), name="del_vuln"),
    path("del_scan/", views.PentestDelete.as_view(), name="del_scan"),
    path("vuln_details/", views.GetPentestVuln.as_view(), name="vuln_details"),
    path("add_list_scan/", views.PentestCreate.as_view(), name="add_list_scan"),
    path("add_vuln_data/", views.AddVulnData.as_view(), name="add_vuln_data"),
    path("add_new_vuln/", views.NewVulnCreate.as_view(), name="add_new_vuln"),
]

tools/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from tools import views

app_name = "tools"

urlpatterns = [
    path("sslscan/", views.SslScanList.as_view(), name="sslscan"),
    path("sslscanlaunch/", views.SslScanLaunch.as_view(), name="sslscanlaunch"),
    path("sslscan_result/", views.SslScanResult.as_view(), name="sslscan_result"),
    path("sslcan_del/", views.SslScanDelete.as_view(), name="sslcan_del"),
    # Nikto requests
    path("nikto/", views.NiktoScanList.as_view(), name="nikto"),
    path("niktolaunch/", views.NiktoScanLaunch.as_view(), name="niktolaunch"),
    path("nikto_result/", views.NiktoScanResult.as_view(), name="nikto_result"),
    path("nikto_scan_del/", views.NiktoScanDelete, name="nikto_scan_del"),
    path("nikto_result_vul/", views.NiktoResultVuln.as_view(), name="nikto_result_vul"),
    path("nikto_vuln_del/", views.NiktoVulnDelete.as_view(), name="nikto_vuln_del"),
    # nmap requests
    path("nmap_scan/", views.NmapScan.as_view(), name="nmap_scan"),
    path("nmap/", views.Nmap.as_view(), name="nmap"),
    path("nmap_result/", views.NmapResult.as_view(), name="nmap_result"),
    path("nmap_scan_del/", views.NmapScanDelete.as_view(), name="nmap_scan_del"),
    # Nmap_Vulners
    path("nmap_vulners_scan/", views.nmap_vulners_scan, name="nmap_scan"),
    path("nmap_vulners/", views.nmap_vulners, name="nmap_vulners"),
    path("nmap_vulners_port_list/", views.nmap_vulners_port, name="nmap_vulners_port"),
]

webscanners/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from webscanners import views, web_views

app_name = "webscanners"

urlpatterns = [
    path("", web_views.Index.as_view(), name="index"),
    path(
        "cookie_add/",
        web_views.AddCookies.as_view(),
        name="cookie_add",
    ),
    path("web_task_launch/", web_views.WebTaskLaunch.as_view(), name="web_task_launch"),
    path(
        "web_scan_schedule/",
        web_views.WebScanSchedule.as_view(),
        name="web_scan_schedule",
    ),
    path(
        "del_web_scan_schedule/",
        web_views.WebScanScheduleDelete.as_view(),
        name="del_web_scan_schedule",
    ),
    path("del_notify/", web_views.DeleteNotify.as_view(), name="del_notify"),
    path("del_all_notify/", web_views.DeleteAllNotify.as_view(), name="del_all_notify"),
    # Dynamic scans
    path("list_vuln/", views.WebScanVulnList.as_view(), name="list_vuln"),
    path("list_scans/", views.WebScanList.as_view(), name="list_scans"),
    path("list_vuln_info/", views.WebScanVulnInfo.as_view(), name="list_vuln_info"),
    path("scan_details/", views.WebScanDetails.as_view(), name="scan_details"),
    path("scan_delete/", views.WebScanDelete.as_view(), name="scan_delete"),
    path("vuln_delete/", views.WebScanVulnDelete.as_view(), name="vuln_delete"),
    path("vuln_mark/", views.WebScanVulnMark.as_view(), name="vuln_mark"),
]

networkscanners/models.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from __future__ import unicode_literals

import uuid

from django.db import models
from django.utils import timezone
from fernet_fields import EncryptedTextField

from user_management.models import Organization, UserProfile


class NetworkScanDb(models.Model):
    class Meta:
        db_table = "networkscandb"
        verbose_name_plural = "Network Scans List"

    scan_id = models.UUIDField(blank=True)
    ip = models.GenericIPAddressField(blank=True, null=True)
    rescan_id = models.TextField(blank=True, null=True)
    scan_date = models.TextField(blank=True)
    scan_status = models.TextField(blank=True)
    project = models.ForeignKey(
        "projects.ProjectDb", on_delete=models.CASCADE, null=True
    )
    total_vul = models.IntegerField(blank=True, null=True)
    critical_vul = models.IntegerField(blank=True, null=True)
    high_vul = models.IntegerField(blank=True, null=True)
    medium_vul = models.IntegerField(blank=True, null=True)
    low_vul = models.IntegerField(blank=True, null=True)
    info_vul = models.IntegerField(blank=True, null=True)
    date_time = models.DateTimeField(blank=True, null=True)
    rescan = models.TextField(blank=True, null=True)
    total_dup = models.TextField(blank=True, null=True)
    scanner = models.TextField(blank=True, null=True)

    created_time = models.DateTimeField(
        auto_now=True,
        blank=True,
    )
    created_by = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        related_name="network_scan_db_created",
    )
    updated_by = models.ForeignKey(
        UserProfile,
        related_name="network_scan_db_updated",
        on_delete=models.SET_NULL,
        null=True,
    )
    is_active = models.BooleanField(default=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, default=1)


class NetworkScanResultsDb(models.Model):
    class Meta:
        db_table = "networkscanresultsdb"
        verbose_name_plural = "Network Scans Data"

    scan_id = models.UUIDField(blank=True)
    project = models.ForeignKey(
        "projects.ProjectDb", on_delete=models.CASCADE, null=True
    )
    vuln_id = models.UUIDField(blank=True)
    title = models.TextField(blank=True)
    date_time = models.DateTimeField(blank=True, null=True)
    severity_color = models.CharField(max_length=256, null=True)
    severity = models.CharField(max_length=256, null=True)
    description = models.TextField(blank=True, null=True)
    solution = models.TextField(blank=True, null=True)
    port = models.TextField(blank=True, null=True)
    ip = models.GenericIPAddressField(blank=True, null=True)
    scanner = models.TextField()
    jira_ticket = models.TextField(null=True, blank=True)
    dup_hash = models.TextField(null=True, blank=True)
    vuln_duplicate = models.TextField(null=True, blank=True)
    vuln_status = models.TextField(null=True, blank=True)
    false_positive_hash = models.TextField(null=True, blank=True)
    false_positive = models.TextField(null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    updated_time = models.DateTimeField(auto_now=True, blank=True, null=True)
    created_time = models.DateTimeField(
        auto_now=True,
        blank=True,
    )
    created_by = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        related_name="network_scan_result_db_created",
    )
    updated_by = models.ForeignKey(
        UserProfile,
        related_name="network_scan_result_db_updated",
        on_delete=models.SET_NULL,
        null=True,
    )
    is_active = models.BooleanField(default=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, default=1)


class TaskScheduleDb(models.Model):
    class Meta:
        db_table = "taskscheduledb"
        verbose_name_plural = "Task Schedule Data"

    task_id = models.TextField(blank=True, null=True)
    target = models.TextField(blank=True, null=True)
    schedule_time = models.TextField(blank=True, null=True)
    project_id = models.TextField(blank=True, null=True)
    scanner = models.TextField(blank=True, null=True)
    periodic_task = models.TextField(blank=True, null=True)
    updated_time = models.DateTimeField(auto_now=True, blank=True, null=True)
    created_time = models.DateTimeField(
        auto_now=True,
        blank=True,
    )
    created_by = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        related_name="tasksch_scan_result_db_created",
    )
    updated_by = models.ForeignKey(
        UserProfile,
        related_name="tasksch_scan_result_db_updated",
        on_delete=models.SET_NULL,
        null=True,
    )
    is_active = models.BooleanField(default=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, default=1)

templates/networkscanners/ipscan.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block body %}

{#<script src="{% static 'matrix-admin-bt4/dist/js/jquery-1.9.1.min.js' %}"></script>#}


        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Infrastructure Scan </h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card">
                                    <form id="start_scan" class="form-horizontal">{% csrf_token %}
                                        <div class="card-body">
                                            <h4 class="card-title"></h4>

                                            <div class="form-group row">
                                                <label class="col-sm-3 text-right control-label col-form-label">URL's</label>
                                                <div class="col-sm-9">
                                                    <textarea class="form-control" name="ip" id="ip" value="{{ ip }}"
                                                              placeholder="192.168.1.1,192.168.1.2"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title"></h5>
                                                <div class="form-group row">
                                                    <label class="col-md-3 m-t-15">Projects</label>
                                                    <div class="col-md-9">
                                                        <select id="project_id" name="project_id"
                                                                class="select2 form-control custom-select"
                                                                style="width: 100%; height:36px;">
                                                            {% for data in all_proj %}
                                                            <option value="{{data.uu_id}}">{{data.project_name}}
                                                            </option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="card-body">
                                                <div class="controls">
                                                    <input type="submit" class="btn btn-primary" value="Launch">
{#                                                    <a href="{% url 'networkscanners:net_scan_schedule' %}"#}
{#                                                       class="btn btn-success">Scan#}
{#                                                        Schedule</a>#}
                                                </div>
                                                <div id='status'></div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <h5 class="card-title">Scanners </h5>
                        </div>
                        <br>
                        <p>Select your scanner(s) from the ones available:</p>
                        <div class="custom-control custom-control-inline">
                            <div class="checkbox inline checkbox-slider--b-flat checkbox-slider--b"
                                 style="width: 200px;">
                                <label>
                                    <input name="optradio1" type="checkbox"><span>OpenVAS</span>
                                </label>
                            </div>
{#                            <div class="checkbox inline checkbox-slider&#45;&#45;b-flat checkbox-slider&#45;&#45;b " style="width: 200px;">#}
{#                            <label>#}
{#                            <input name="optradio2" type="checkbox"><span>Nmap</span>#}
{#                            </label>#}
                            <!--</div>-->
{#                            <div class="checkbox inline checkbox-slider--b-flat checkbox-slider--b"#}
{#                                 style="width: 200px;">#}
{#                                <label>#}
{#                                    <input name="optradio2" type="checkbox"><span>NMAP</span>#}
{#                                </label>#}
{#                            </div>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>



<script type="text/javascript">
setInterval('autoRefresh_div()', {{ settings.REFRESH_TIMER }}000);

$(document).on('submit', '#start_scan', function(e){
    var opt = false;
    e.preventDefault();
    if ($('[name="optradio1"]').is(':checked')){
        opt = true;
        $.ajax({
            type:'POST',
            url:'{% url 'networkscanners:launch_scan' %}',
            data:{
                ip:$('#ip').val(),
                project_id:$('#project_id').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(){
            }
        });
        this.reset();
    }
    else if ($('[name="optradio2"]').is(':checked')){
        opt = true;
        $.ajax({
            type:'POST',
            url:'{% url 'tools:nmap' %}',
            data:{
                ip:$('#ip').val(),
                project_id:$('#project_id').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(){
            }
        });
    }
    else if ($('[name="optradio3"]').is(':checked')){
        opt = true;
        $.ajax({
            type:'POST',
            url:'{% url 'tools:nmap_vulners' %}',
            data:{
                ip:$('#ip').val(),
                project_id:$('#project_id').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(){
            }
        });
    }
    if (opt) {
        $('#status').text('Scan launched.').css ({'color': '#5bb75b', 'margin-left': '200px'});
    } else {
        $('#status').text("The scan can't launched: no scanner selected.").css({'color': '#b94a48', 'margin-left': '200px'});
    }
});



</script>

{% endblock %}

templates/networkscanners/nv_settings.html
{% extends 'dashboard/base.html' %}

{% block body %}


        <div class="row justify-content-md-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">NMAP Vulners Setting</h1>
                        </div>
                        <br>
                        <div class="card">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <form id="nv" method="POST" action="{% url 'networkscanners:nv_details' %}">{% csrf_token %}
                        <div class="form-group row">
                            <span class="icon"> <i class="icon-align-justify"></i></span>
                            <label class="col-sm-4 col-form-label">NMAP Vulners Settings Enable</label>
                            <span class="checkbox inline checkbox-slider--b-flat checkbox-slider--b" style="float: right;">
                                <label>
                                    <input name="nv_enabled" id="nv_enabled" {% if nv_enabled == "True" %} value="on" checked="checked" {% endif %} type="checkbox"><span></span>
                                </label>
                            </span>
                        </div>
                        <div class="widget-content nopadding">
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Version detection</label>
                                <div class="controls">
                                    <div class="checkbox inline checkbox-slider--b-flat checkbox-slider--b">
                                        <label>
                                            <input name="nv_version" id="nv_version" {% if nv_version == "True" %} value="on" checked="checked" {% endif %} type="checkbox"><span></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Treat all hosts as online<br/><small><em>Skip host discovery</em></small></label>
                                <div class="controls">
                                    <div class="checkbox inline checkbox-slider--b-flat checkbox-slider--b">
                                        <label>
                                            <input name="nv_online" id="nv_online" {% if nv_online == "True" %} value="on" checked="checked" {% endif %} type="checkbox"><span></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Set timing template (higher is faster)<br/><small><em>Value between 0 and 5</em></small></label>
                                <div class="controls">
                                    <select id="nv_timing" name="nv_timing" class="select2 form-control custom-select" data-live-search="true">
                                        <option value="0"{% if nv_timing == 0 %} selected="selected"{% endif %}>0</option>
                                        <option value="1"{% if nv_timing == 1 %} selected="selected"{% endif %}>1</option>
                                        <option value="2"{% if nv_timing == 2 %} selected="selected"{% endif %}>2</option>
                                        <option value="3"{% if nv_timing == 3 %} selected="selected"{% endif %}>3</option>
                                        <option value="4"{% if nv_timing == 4 %} selected="selected"{% endif %}>4</option>
                                        <option value="5"{% if nv_timing == 5 %} selected="selected"{% endif %}>5</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </div>
                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

templates/networkscanners/setting_form.html
{% extends 'dashboard/base.html' %}

{% block body %}


        <div class="row justify-content-md-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">OpenVAS Setting</h1>
                        </div>
                        <br>
                        <div class="card">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <div class="widget-box">
                                        <form  id="openvas" method="POST" action="{% url 'networkscanners:openvas_details' %}">{% csrf_token %}
                                            <div class="form-group row">
                                                <label class="col-sm-4 col-form-label">Enable</label>
                                                <div class="checkbox inline checkbox-slider--b-flat checkbox-slider--b" style="float: right;">
                                                    <label>
                                                        <input name="openvas_enabled" {% if openvas_enabled == "True" %} value="on" checked="checked" {% endif %} type="checkbox"><span></span>
                                                    </label>
                                                </div>
                                            </div>
                                                <div class="form-group row">
                                                    <label class="col-sm-4 col-form-label">Host<br/><small><em>(OpenVAS Manager)</em></small></label>
                                                    <div class="controls">
                                                        <input type="text" name="openvas_host" value="{{ openvas_host }}" class="form-control" placeholder="Host"/>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-sm-4 col-form-label">Port</em></small></label>
                                                    <div class="controls">
                                                        <input type="text" name="openvas_port" value="{{ openvas_port }}" class="form-control" placeholder="Port"/>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-sm-4 col-form-label">User</label>
                                                    <div class="controls">
                                                        <input type="text" name="openvas_user" value="{{ openvas_user }}" class="form-control" placeholder="User Id"/>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-sm-4 col-form-label">Password</label>
                                                    <div class="controls">
                                                        <input type="password" name="openvas_password" value="{{ openvas_password }}" class="form-control" placeholder="Password"/>
                                                    </div>
                                                </div>
                                                <div class="form-actions">
                                                    <button type="submit" class="btn btn-success">Save</button>
                                                </div>
                                                </form>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}