cicd/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from cicd import views

app_name = "cicd"

urlpatterns = [
    path("", views.CicdScanList.as_view(), name="cicd_list"),
    path("scannercmd/", views.ScannerCommand.as_view(), name="scannercmd"),
    path("createpolicies/", views.CreatePolicies.as_view(), name="createpolicies"),
    path("deletepolicies/", views.PoliciesDelete.as_view(), name="deletepolicies"),
    path(
        "policiesedit/<str:uu_id>/", views.PoliciesEdit.as_view(), name="policiesedit"
    ),
]

compliance/dockle/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from compliance.dockle import views

app_name = "dockle"

urlpatterns = [
    # Bandit scan list
    path("dockle_list/", views.DockleScanList.as_view(), name="dockle_list"),
    path("dockle_all_vuln/", views.DockleVulnList.as_view(), name="dockle_all_vuln"),
    path("dockle_vuln_data/", views.DockleVulnData.as_view(), name="dockle_vuln_data"),
    path("dockle_details/", views.DockleDetails.as_view(), name="dockle_details"),
    path("del_dockle/", views.DockleDelete.as_view(), name="del_dockle"),
    path("dockle_del_vuln/", views.DockleVulnDelete.as_view(), name="dockle_del_vuln"),
    path("export/", views.export, name="export"),
]

compliance/inspec/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.urls import include, path

from compliance.inspec import views

app_name = "inspec"

urlpatterns = [
    # Bandit scan list
    path("inspec_list/", views.InspecScanList.as_view(), name="inspec_list"),
    path("inspec_all_vuln/", views.InspecVulnList.as_view(), name="inspec_all_vuln"),
    path("inspec_vuln_data/", views.InspecVulnData.as_view(), name="inspec_vuln_data"),
    path("inspec_details/", views.InspecDetails.as_view(), name="inspec_details"),
    path("del_inspec/", views.InspecDelete.as_view(), name="del_inspec"),
    path("inspec_del_vuln/", views.InspecVulnDelete.as_view(), name="inspec_del_vuln"),
    path("export/", views.export, name="export"),
]

report_upload/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.
from django.urls import include, path

from report_upload import views

app_name = "report_upload"

urlpatterns = [
    path("upload/", views.Upload.as_view(), name="upload"),
]

compliance/dockle/views.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

import hashlib

from django.shortcuts import HttpResponse, HttpResponseRedirect, render
from django.urls import reverse
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from compliance.models import DockleScanDb, DockleScanResultsDb
from staticscanners.resources import dockleResource
from user_management import permissions


def export(request):
    """
    :param request:
    :return:
    """

    if request.method == "POST":
        scan_id = request.POST.get("scan_id")
        report_type = request.POST.get("type")

        dockle_resource = dockleResource()
        queryset = DockleScanResultsDb.objects.filter(scan_id=scan_id)
        dataset = dockle_resource.export(queryset)
        if report_type == "csv":
            response = HttpResponse(dataset.csv, content_type="text/csv")
            response["Content-Disposition"] = 'attachment; filename="%s.csv"' % scan_id
            return response
        if report_type == "json":
            response = HttpResponse(dataset.json, content_type="application/json")
            response["Content-Disposition"] = 'attachment; filename="%s.json"' % scan_id
            return response
        if report_type == "yaml":
            response = HttpResponse(dataset.yaml, content_type="application/x-yaml")
            response["Content-Disposition"] = 'attachment; filename="%s.yaml"' % scan_id
            return response


class DockleScanList(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "compliance/dockle/docklescans_list.html"

    permission_classes = (IsAuthenticated,)

    def get(self, request):
        all_dockle_scan = DockleScanDb.objects.filter()

        return render(
            request,
            "compliance/dockle/docklescans_list.html",
            {"all_dockle_scan": all_dockle_scan},
        )


class DockleVulnList(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "compliance/dockle/docklescan_list_vuln.html"

    permission_classes = (IsAuthenticated,)

    def get(self, request):
        scan_id = request.GET["scan_id"]

        dockle_all_vuln = DockleScanResultsDb.objects.filter(scan_id=scan_id)
        dockle_all_audit = DockleScanResultsDb.objects.filter(scan_id=scan_id)

        all_compliance = DockleScanDb.objects.filter(scan_id=scan_id)

        return render(
            request,
            "compliance/dockle/docklescan_list_vuln.html",
            {
                "dockle_all_vuln": dockle_all_vuln,
                "dockle_all_audit": dockle_all_audit,
                "all_compliance": all_compliance,
            },
        )


class DockleVulnData(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "compliance/dockle/docklescan_vuln_data.html"

    permission_classes = (IsAuthenticated, permissions.IsAnalyst)

    def get(self, request):
        scan_id = request.GET["scan_id"]
        vuln_id = request.GET["vuln_id"]
        dockle_vuln_data = DockleScanResultsDb.objects.filter(
            scan_id=scan_id,
            vuln_id=vuln_id,
            vuln_status="Open",
            false_positive="No",
        )

        vuln_data_closed = DockleScanResultsDb.objects.filter(
            scan_id=scan_id,
            vuln_id=vuln_id,
            vuln_status="Closed",
            false_positive="No",
        )
        false_data = DockleScanResultsDb.objects.filter(
            scan_id=scan_id, vuln_id=vuln_id, false_positive="Yes"
        )

        return render(
            request,
            "compliance/dockle/docklescan_vuln_data.html",
            {
                "dockle_vuln_data": dockle_vuln_data,
                "false_data": false_data,
                "vuln_data_closed": vuln_data_closed,
            },
        )

    def post(self, request):
        false_positive = request.POST.get("false")
        status = request.POST.get("status")
        vuln_id = request.POST.get("vuln_id")
        scan_id = request.POST.get("scan_id")
        DockleScanResultsDb.objects.filter(vuln_id=vuln_id, scan_id=scan_id).update(
            false_positive=false_positive, vuln_status=status
        )

        if false_positive == "Yes":
            vuln_info = DockleScanResultsDb.objects.filter(
                scan_id=scan_id, vuln_id=vuln_id
            )
            for vi in vuln_info:
                Name = vi.Name
                NamespaceName = vi.NamespaceName
                Severity = vi.Severity
                dup_data = Name + Severity + NamespaceName
                false_positive_hash = hashlib.sha256(
                    dup_data.encode("utf-8")
                ).hexdigest()
                DockleScanResultsDb.objects.filter(
                    vuln_id=vuln_id, scan_id=scan_id
                ).update(
                    false_positive=false_positive,
                    vuln_status=status,
                    false_positive_hash=false_positive_hash,
                )

        return HttpResponseRedirect(
            reverse("dockle:dockle_vuln_data")
            + "?scan_id=%s&test_name=%s" % (scan_id, vuln_id)
        )


class DockleDetails(APIView):
    enderer_classes = [TemplateHTMLRenderer]
    template_name = "compliance/dockle/dockle_vuln_details.html"

    permission_classes = (IsAuthenticated,)

    def get(self, request):
        scan_id = request.GET["scan_id"]
        vuln_id = request.GET["vuln_id"]

        dockle_vuln_details = DockleScanResultsDb.objects.filter(
            scan_id=scan_id, vuln_id=vuln_id
        )
        return render(
            request,
            "compliance/dockle/dockle_vuln_details.html",
            {
                "dockle_vuln_details": dockle_vuln_details,
            },
        )


class DockleDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "compliance/dockle/docklescans_list.html"

    permission_classes = (
        IsAuthenticated,
        permissions.IsAnalyst,
    )

    def post(self, request):
        scan_id = request.POST.get("scan_id")
        scan_item = str(scan_id)
        value = scan_item.replace(" ", "")
        value_split = value.split(",")
        split_length = value_split.__len__()
        # print "split_length", split_length
        for i in range(0, split_length):
            scan_id = value_split.__getitem__(i)
            item = DockleScanDb.objects.filter(scan_id=scan_id)
            item.delete()
            item_results = DockleScanResultsDb.objects.filter(scan_id=scan_id)
            item_results.delete()
        # messages.add_message(request, messages.SUCCESS, 'Deleted Scan')
        return HttpResponseRedirect(reverse("dockle:dockle_list"))


class DockleVulnDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "compliance/dockle/dockle_vuln_details.html"

    permission_classes = (IsAuthenticated, permissions.IsAnalyst)

    def post(self, request):
        vuln_id = request.POST.get(
            "del_vuln",
        )
        scan_id = request.POST.get(
            "scan_id",
        )
        scan_item = str(vuln_id)
        value = scan_item.replace(" ", "")
        value_split = value.split(",")
        split_length = value_split.__len__()
        print("split_length"), split_length
        for i in range(0, split_length):
            vuln_id = value_split.__getitem__(i)
            delete_vuln = DockleScanResultsDb.objects.filter(vuln_id=vuln_id)
            delete_vuln.delete()
        all_dockle_data = DockleScanResultsDb.objects.filter(scan_id=scan_id)

        total_vul = len(all_dockle_data)
        total_high = len(all_dockle_data.filter(Severity="High"))
        total_medium = len(all_dockle_data.filter(Severity="Medium"))
        total_low = len(all_dockle_data.filter(Severity="Low"))
        total_duplicate = len(all_dockle_data.filter(vuln_duplicate="Yes"))

        DockleScanDb.objects.filter(scan_id=scan_id).update(
            total_vuln=total_vul,
            high_vul=total_high,
            medium_vul=total_medium,
            low_vul=total_low,
            total_dup=total_duplicate,
        )

        return HttpResponseRedirect(
            reverse("dockle:dockle_all_vuln" + "?scan_id=%s" % scan_id)
        )

compliance/views.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

templates/compliance/inspec/inspecscan_list_vuln.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block body %}

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <div>
                                <h5>Compliance Summary</h5>
                                <h5 class="card-subtitle"></h5>
                            </div>
                        </div>
                        <div class="row">
                            <!-- column -->
                            <div class="col-sm-6 col-md-6">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Audit</th>
                                            <th>Status</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><a href="#">Total Nodes</a></td>
                                            <td><span class="badge badge-pill badge-dark">{% for data in all_compliance %}{{data.total_vuln}}{% endfor %}</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><a href="#">Failed Nodes</a></td>
                                            <td><span class="badge badge-pill badge-danger">{% for data in all_compliance %}{{data.inspec_failed}}{% endfor %}</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><a href="#">Passed Nodes</a></td>
                                            <td><span class="badge badge-pill badge-success">{% for data in all_compliance %}{{data.inspec_passed}}{% endfor %}</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><a href="#">Skipped Nodes</a></td>
                                            <td><span class="badge badge-pill badge-info">{% for data in all_compliance %}{{data.inspec_skipped}}{% endfor %}</span>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-6">
                                <canvas id="webscans"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <div>
                                <h5>Audit List</h5>
                                <h5 class="card-subtitle"></h5>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <!-- column -->
                            <div class="col-lg-12">
                                <div class="table-responsive">
                                    <table id="data_table" class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Controls ID</th>
                                            <th>Controls Descriptions</th>
                                            <th>Severity</th>
                                            <th>Audit Text</th>
                                            <th>Fix</th>
                                        </tr>
                                        </thead>
                                        <tbody>{% for data in inspec_all_vuln %}
                                        <tr data-target="#">
                                            <td>{{data.controls_id}}</td>
                                            <td>{{data.controls_title}}</td>
                                            <td>{{data.controls_tags_severity}}</td>
                                            <td>{{data.controls_tags_audit}}</td>
                                            <td>{{data.controls_tags_fix}}</td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <div>
                                <h5>Audit List</h5>
                                <h5 class="card-subtitle"></h5>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <!-- column -->
                            <div class="col-lg-12">
                                <div class="table-responsive">
                                    <table id="data_table" class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Audit</th>
                                            <th>Status</th>

                                        </tr>
                                        </thead>
                                        <tbody>{% for data in inspec_all_audit %}
                                        <tr data-target="#">
                                            <td>
                                                <a href="{% url 'inspec:inspec_details' %}?scan_id={{data.scan_id}}&vuln_id={{data.vuln_id}}">{{data.controls_results_code_desc}}</a>
                                            </td>
                                            <td><span
                                                    class="badge badge-pill badge-{{data.vul_col}}">{{data.controls_results_status}}</span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



<script type="text/javascript" src="{% static 'js/Chart.js' %}"></script>
<script type="text/javascript">
    var ctx = document.getElementById("webscans").getContext('2d');
    var webscans = new Chart(ctx, {
        type: 'doughnut',
        data: {
                    datasets: [{
                        data: [
                           {% for data in all_compliance %}{{data.inspec_failed}}{% endfor %},
                            {% for data in all_compliance %}{{data.inspec_passed}}{% endfor %},
                            {% for data in all_compliance %}{{data.inspec_skipped}}{% endfor %},

                        ],
                        backgroundColor: [
                            '#db5565', '#28b779', '#3a87ad'

                        ],
                        label: 'Venerability'
                    }],
                    labels: [
                        'Failed',
                        'Passed',
                        'Skipped',
                    ]
                },
        options: {
            responsive: true,
            title: {
                            display: true,
                            text: 'Compliance Summary'
                        }
        }
    });






</script>

{% endblock %}

templates/compliance/inspec/inspecscans_list.html
{% extends 'dashboard/base.html' %}

{% block body %}
    <script type="text/javascript">

        $("#checkAll").change(function () {
            $("input:checkbox").prop('checked', $(this).prop("checked"));
        });
        $(document).ready(function () {
            $('.btn-danger').click(function () {
                if (confirm('Are you sure you want to delete this?')) {
                    var scan_id = ['a7af5b68-b661-45ad-90fd-ffa27526cdce'];
                    $.each($("input[name='del_scan_id']:checked"), function () {
                        scan_id.push($(this).val());
                    });

                    var json_scanid = scan_id.join(", ");
                    $.ajax({
                        type: 'POST',
                        <!--contentType: 'application/json; charset=utf-8',-->
                        url: '{% url 'inspec:del_inspec' %}',
                        data: {
                            scan_id: json_scanid,
                            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                        },
                        sucess: function () {

                        }
                    });
                    setTimeout(location.reload(), 6000);
                }
            });

        });


    </script>


    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="float-right">
                       {% if user.is_superuser == True or user.role.id == 2 %}
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="{% url 'report_upload:upload' %}" class="btn btn-primary btn-mini"><i
                                    class="icon-upload-alt"></i> Upload </a>
                        </div>
                        <button type="button" class="btn btn-danger btn-mini" onclick="">Delete Selected</button>
                        {% endif %}
                    </div>
                    <br>
                    <br>
                    <br>
                    <div class="d-md-flex align-items-center">
                        <h1 class="card-title">Inspec Scan List</h1>
                    </div>
                    <br>
                    <div class="row">
                        <div class="table-responsive">
                            <table id="data_table" class="table table-bordered data-table">
                                <thead>
                                <tr>
                                    <th><label class="customcheckbox m-b-20">
                                        <input type="checkbox" id="mainCheckbox">
                                        <span class="checkmark"></span>
                                    </label></th>
                                    <th>Project Name</th>
                                    <th>Status</th>
                                    <th>Date Time</th>
                                    <th>Total Complained</th>
                                    <th>Failed</th>
                                    <th>Passed</th>
                                    <th>Skipped</th>
                                    <th>Duplicates</th>
                                </tr>
                                </thead>
                                <tbody>{% for data in all_inspec_scan %}
                                    <tr data-target="#">
                                        <td>
                                            <form>
                                                <label class="customcheckbox">
                                                    <input type="checkbox" class="listCheckbox"
                                                           value="{{ data.scan_id }}"
                                                           name="del_scan_id"
                                                           onClick="reload">
                                                    <span class="checkmark"></span>
                                                </label>
                                            </form>
                                        </td>
                                        <td>
                                            <a href="{% url 'inspec:inspec_all_vuln' %}?scan_id={{ data.scan_id }}">{{ data.project_name }}</a>
                                        </td>
                                        {% csrf_token %}
                                        <td width="20%">
                                            <div>
                                                <div class="d-flex no-block align-items-center">
                                                    <span>{{ data.scan_status }}{{ data.vul_status }}% Completed</span>
                                                </div>
                                                <div class="progress{% if data.scan_status != '100.0' %} active progress-striped{% endif %}">
                                                    <div class="progress-bar progress-bar-striped" role="progressbar"
                                                         style="width: {{ data.scan_status }}{{ data.vul_status }}%"
                                                         aria-valuenow="10" aria-valuemin="0"
                                                         aria-valuemax="100"></div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>{{ data.date_time }}</td>
                                        <td><span class="badge badge-pill badge-dark">{{ data.total_vuln }}</span></td>
                                        <td><span class="badge badge-pill badge-danger">{{ data.inspec_failed }}</span>
                                        </td>
                                        <td><span class="badge badge-pill badge-success">{{ data.inspec_passed }}</span>
                                        </td>
                                        <td><span class="badge badge-pill badge-info">{{ data.inspec_skipped }}</span>
                                        </td>
                                        <td><span class="badge badge-pill badge-secondary">{{ data.total_dup }}</span>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}